version: "3.1"
services:

  wordpress:
    image: wordpress:php7.1
    depends_on:
      - wp_db
    restart: unless-stopped
    volumes:
        - ${PWD}:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=wp_db:3306
      - WORDPRESS_DB_PASSWORD=merch_password
      - WORDPRESS_DB_NAME=merch_wordpress_database
      - WORDPRESS_TABLE_PREFIX=merch_wp
    ports:
      - 80:80

  wp_db:
    image: mariadb
    restart: unless-stopped
    volumes:
      - ${PWD}/volumes/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=merch_password
      - MYSQL_PASSWORD=merch_password
      - MYSQL_DATABASE=merch_wordpress_database
